#!/usr/bin/env python3
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


def parse_kernelbench_task(task: str):
    p = Path(task)
    level = None
    problem_id = None

    for part in p.parts:
        m = re.fullmatch(r"level(\d+)", part)
        if m:
            level = int(m.group(1))

    m = re.match(r"(\d+)_", p.name)
    if m:
        problem_id = int(m.group(1))

    if level is None or problem_id is None:
        raise ValueError(f"Cannot parse KernelBench level/problem_id from task: {task}")

    return level, problem_id


def iter_strings(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for v in obj.values():
            yield from iter_strings(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from iter_strings(v)


def extract_python_code(text: str):
    if not text:
        return None

    # Prefer fenced python block.
    m = re.search(r"```(?:python|py)?\s*\n(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if m:
        text = m.group(1)

    # If the JSON stores a long answer, cut from first useful Python marker.
    markers = [
        "import torch",
        "from torch",
        "import triton",
        "from triton",
        "class ModelNew",
        "class Model",
    ]

    start = None
    for marker in markers:
        idx = text.find(marker)
        if idx != -1:
            if start is None or idx < start:
                start = idx

    if start is not None:
        text = text[start:]

    text = text.strip()

    if "class ModelNew" not in text:
        return None

    return repair_common_codegen_errors(text)


def repair_common_codegen_errors(code: str):
    # Remove standalone artifact filename lines accidentally emitted by the model.
    # These often appear inside CUDA source strings and cause nvcc errors like:
    #   cuda.cu(4): error: this declaration has no storage class or type specifier
    bad_filename_lines = {
        "kernel.h",
        "kernel.cu",
        "main.cpp",
        "matrix_multiply.cu",
        "matrix_multiply.cpp",
        "matrix_multiply.h",
    }
    cleaned_lines = []
    for line in code.splitlines():
        stripped = line.strip().strip("`").strip()
        if stripped in bad_filename_lines:
            continue
        cleaned_lines.append(line)
    code = "\n".join(cleaned_lines)

    # Very common wrong PyTorch extension API generated by LLMs:
    # load_inline(..., sources=[cpp_source, cuda_source], ...)
    # Correct API:
    # load_inline(..., cpp_sources=[cpp_source], cuda_sources=[cuda_source], ...)
    replacements = [
        (
            r"sources\s*=\s*\[\s*cpp_source\s*,\s*cuda_source\s*\]",
            "cpp_sources=[cpp_source], cuda_sources=[cuda_source]",
        ),
        (
            r"sources\s*=\s*\[\s*cuda_source\s*,\s*cpp_source\s*\]",
            "cpp_sources=[cpp_source], cuda_sources=[cuda_source]",
        ),
        (
            r"sources\s*=\s*\[\s*source_cpp\s*,\s*source_cuda\s*\]",
            "cpp_sources=[source_cpp], cuda_sources=[source_cuda]",
        ),
        (
            r"sources\s*=\s*\[\s*source_cuda\s*,\s*source_cpp\s*\]",
            "cpp_sources=[source_cpp], cuda_sources=[source_cuda]",
        ),
    ]

    for pat, rep in replacements:
        code = re.sub(pat, rep, code)

    return code


def copy_candidates_from_artifacts(artifacts: Path, out: Path):
    copied = 0
    seen = set()

    def write_candidate(code: str, src: Path):
        nonlocal copied
        code = extract_python_code(code)
        if not code:
            return

        key = hash(code)
        if key in seen:
            return
        seen.add(key)

        dst = out / f"candidate_{copied:04d}.py"
        dst.write_text(code)
        print("[ksearch-adapter] copied candidate:", src, "->", dst)
        copied += 1

    # 1) direct .py files
    for py in artifacts.rglob("*.py"):
        try:
            write_candidate(py.read_text(errors="ignore"), py)
        except Exception as e:
            print("[ksearch-adapter] WARN reading py:", py, e)

    # 2) K-Search saved solution JSON files
    for js in artifacts.rglob("*.json"):
        try:
            obj = json.loads(js.read_text(errors="ignore"))
        except Exception as e:
            print("[ksearch-adapter] WARN reading json:", js, e)
            continue

        for s in iter_strings(obj):
            if "class ModelNew" in s or "load_inline" in s or "```python" in s:
                write_candidate(s, js)

    return copied


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--rounds", type=int, default=1)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--model-name", default=os.environ.get("KSEARCH_MODEL_NAME", "qwen14b"))
    ap.add_argument("--base-url", default=os.environ.get("KSEARCH_BASE_URL", "http://127.0.0.1:8000/v1"))
    ap.add_argument("--target-gpu", default=os.environ.get("KSEARCH_TARGET_GPU", "RTX PRO 6000"))
    ap.add_argument("--language", default=os.environ.get("KSEARCH_LANGUAGE", "python"))
    args = ap.parse_args()

    root = Path.cwd()
    repo = root / "third_party" / "K-Search"
    out = Path(args.out).resolve()
    artifacts = out / "ksearch_artifacts"
    out.mkdir(parents=True, exist_ok=True)
    artifacts.mkdir(parents=True, exist_ok=True)

    level, problem_id = parse_kernelbench_task(args.task)

    script = repo / "generate_kernels_and_eval.py"
    if not script.exists():
        raise FileNotFoundError(f"Missing K-Search entrypoint: {script}")

    env = os.environ.copy()
    env.setdefault("OPENAI_API_KEY", "EMPTY")
    env.setdefault("LLM_API_KEY", "EMPTY")
    env.setdefault("WANDB_MODE", "disabled")

    kb_root = root / "third_party" / "KernelBench"
    py_paths = [
        repo,
        kb_root,
        kb_root / "src",
        kb_root / "KernelBench",
    ]
    env["PYTHONPATH"] = ":".join(str(x) for x in py_paths if x.exists()) + ":" + env.get("PYTHONPATH", "")

    cmd = [
        sys.executable,
        str(script),
        "--task-source", "kernelbench",
        "--model-name", args.model_name,
        "--base-url", args.base_url,
        "--api-key", "EMPTY",
        "--language", args.language,
        "--target-gpu", args.target_gpu,
        "--max-opt-rounds", str(args.rounds),
        "--kernelbench-level", str(level),
        "--kernelbench-problem-id", str(problem_id),
        "--kernelbench-eval-mode", "local",
        "--kernelbench-num-correct-trials", "1",
        "--kernelbench-num-perf-trials", "1",
        "--save-solutions",
        "--artifacts-dir", str(artifacts),
    ]

    print("[ksearch-adapter] task:", args.task)
    print("[ksearch-adapter] level:", level, "problem_id:", problem_id)
    print("[ksearch-adapter] cmd:", " ".join(cmd), flush=True)

    rc = subprocess.call(cmd, cwd=str(repo), env=env)
    print("[ksearch-adapter] return code:", rc)

    copied = copy_candidates_from_artifacts(artifacts, out)

    if copied == 0:
        print("[ksearch-adapter] WARNING: no ModelNew candidate found under", artifacts)
    else:
        print(f"[ksearch-adapter] copied {copied} candidate(s)")

    # K-Search 자체 eval 실패 여부와 관계없이 unified final_eval로 넘긴다.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
